### ISSUE TITLE
BitFlyerDotNet.Tradingでの注文について

### ISSUE THREAD

**Issue by hayanobiton** [fiatsasia/BitFlyerDotNet#3]
BitFlyerDotNet.Tradingにおいて、CreateMarketPriceOrderが見つかりませんが、注文はどのようにするのですか？

つまり、ブログを拝見すると、
var account = new TradingAcount(BfProductCCode.FXBTCJPY);
account.login(key,sercrt);
として、
account.CreateMarketPriceOrder（・・・）で注文するようですが、このCreateMarketPriceOrderがありません。

BitFlyerDotNet.Tradingの注文方法をおしえていただけませんでしょうか。

**Comment by fiatsasia** [comment]
注文リクエストを作成する方法が変更になっています。
以下のTradingOrderFactoryを使用して注文を作成して下さい。

https://github.com/fiatsasia/BitFlyerDotNet/blob/master/BitFlyerDotNet.Trading/TradeOrderFactory.cs

また、大まかな流れは、以下のテストコードをご覧下さい。
https://github.com/fiatsasia/BitFlyerDotNet/blob/master/Tests/TradingApiTests/UnitTest1.cs

**Comment by fiatsasia** [comment]
Version 2.1.0のリリースに併せてサンプルアプリケーションを追加しました。
https://github.com/fiatsasia/BitFlyerDotNet/tree/master/Samples/TradingApiSample
