### ISSUE TITLE
Error converting value "Spot" to type 'BitFlyerDotNet.LightningApi.BfMarket'. Path '[0].market_type', line 1, position 47.

### ISSUE THREAD

**Issue by hayanobiton** [fiatsasia/BitFlyerDotNet#4]
realtimeapiを使用ていていましたが、アップデート後から、
var factory = new RealtimeSourceFactory();
を実行すると、タイトルのようなエラーが発生します

ソースを確認をしたところ、GetMarkets.csの18行目が
 public BfMarket MarketType { get; private set; }
となっておりました。

Enums.csに新たに追加したものが、public enum BfMarketType{}　なので、

 public BfMarketType MarketType { get; private set; }

の誤りではないでしょうか

**Comment by fiatsasia** [comment]
ご指摘ありがとうございます。

該当箇所を修正し、動作を確認しました。2.1.7として、NuGetににリリースしました。
