### ISSUE TITLE
System.ArgumentException: 'An item with the same key has already been added. Key: BTCJPY'

### ISSUE THREAD

**Issue by hayanobiton** [fiatsasia/BitFlyerDotNet#6]
BitFlyerDotNet.LightningApi3.01を使用していますが、今朝（2020.09.30)より、Realtime通信を実行すると、タイトルのエラーが発生します。

デバックをおこなったところ、
void GetAvailableMarkets()
{
    _availableMarkets.Clear();
     using (var client = new BitFlyerClient())
     {
        client.GetAvailableMarkets().ForEach(market => _availableMarkets.Add(market.ProductCode, market.Symbol));
      }
 }
で例外が発生しました。

そして、 BitFlyerClientExtensions　ー　public static List<(BfProductCode ProductCode, string Symbol)> GetAvailableMarkets(this BitFlyerClient client)　内の 

var result = new List<(BfProductCode ProductCode, string Symbol)>();

で、BTCJPYが二重取得しております。

![result](https://user-images.githubusercontent.com/34781980/94681198-01fb7d00-035e-11eb-9e5c-774629c22706.png)

昨日まで問題なく動いていたので、bitFlyer側の仕様変更によるものかどうかわかりませんが、ご報告いたします

**Comment by fiatsasia** [comment]
ご報告ありがとうございます。

bitFlyer EU がクロスボーダー取引を開始した影響によるものです。
https://scrapbox.io/BitFlyerDotNet/%E6%9B%B4%E6%96%B0%E5%B1%A5%E6%AD%B4
