### ISSUE TITLE
JSON integer 2147700412 is too large or small for an Int32

### ISSUE THREAD

**Issue by hayanobiton** [fiatsasia/BitFlyerDotNet#7]
約定データのDeserializeObject処理で、タイトルのようなエラーが発生します。

**Comment by fiatsasia** [comment]
約定ID(Execution ID)がintの範囲を超えてしまったためです。4.0.0RC1で修正しました。nuget package は後ほど更新します。

**Comment by fiatsasia** [comment]
4.0.0をリリースしました。nuget packageも更新しました。
